version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cache_redis
    restart: always
    ports:
      - "6379:6379"

  auth-service:
    image: auth-service:1.0
    build: ./microservices-lab/auth-service 
    container_name: auth_service
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.example

volumes:
  pgdata: