version: '3.8'
services:
  auth_service:
    build: ./auth-service
    container_name: auth_service
    restart: always
    env_file:
      - ./auth-service/.env
    environment:
      - DEBUG=${DEBUG}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service:/app

  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: auth_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
